# Generated by Django 3.2.7 on 2021-12-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211228_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Host',
            new_name='host',
        ),
    ]
